/**
 * @author			: kiran
 * @created date	: 05 oct 2016
 * @modified by		: kiran
 * @modified date	: 18 oct 2016
 */
package com.nviera.constants;

public final class QueryConstants {
	/**
	 * Admin Queries
	 */
	public static final String SELECT_ADMIN_ID_DETAILS = "SELECT ADMIN_DETAILS_USERID, ADMIN_DETAILS_PASSWORD FROM ADMIN_DETAILS ";
	/**
	 * Customer Queries
	 */
	public static final String SELECT_CUSTOMER_DETAILS  = "SELECT CUSTOMER_DETAILS_ID, CUSTOMER_DETAILS_NAME,CUSTOMER_DETAILS_PASSWORD,CUSTOMER_DETAILS_SHOP_NAME,CUSTOMER_DETAILS_PLACE,CUSTOMER_DETAILS_CITY,CUSTOMER_DETAILS_WALLET_AMOUNT,CUSTOMER_DETAILS_PSWD_RESET,CUSTOMER_DETAILS_FOODITEMS,CUSTOMER_DETAILS_NONFOODITEMS,CUSTOMER_DETAILS_ITEMS_PERCENT_CHANGE,CUSTOMER_DETAILS_PRODUCT_CHANGE FROM CUSTOMER_DETAILS WHERE CUSTOMER_DETAILS_STA ='A' ";
	public static final String CUSTOMER_CREATION = "INSERT INTO  CUSTOMER_DETAILS(CUSTOMER_DETAILS_NAME,CUSTOMER_DETAILS_PASSWORD,CUSTOMER_DETAILS_SHOP_NAME,CUSTOMER_DETAILS_PLACE,CUSTOMER_DETAILS_CITY,CUSTOMER_DETAILS_WALLET_AMOUNT,CUSTOMER_DETAILS_FOODITEMS,CUSTOMER_DETAILS_NONFOODITEMS,CUSTOMER_DETAILS_SINCE,CUSTOMER_DETAILS_LAST_RECHARGE,CUSTOMER_DETAILS_STA,CUSTOMER_DETAILS_CREATED_BY,CUSTOMER_DETAILS_CREATED_ON,CUSTOMER_DETAILS_CREATED_TIME) VALUES ";
	public static final String CUSTOMER_UPDATION = "UPDATE CUSTOMER_DETAILS SET ";
	public static final String CUSTOMER_TRANS_INSERT = "INSERT INTO CUST_TRANSACTIONS (CUST_TRANSACTIONS_CUST_ID,CUST_TRANSACTIONS_TOTAL_AMOUNT_PURCHASED,CUST_TRANSACTIONS_CREATED_BY,CUST_TRANSACTIONS_CREATED_ON,CUST_TRANSACTIONS_CREATED_TIME) VALUES";
	/**
	 * User Queries
	 */
	public static final String MOBILE_VALIDATE = "SELECT USER_DETAILS_ID,USER_DETAILS_MOBILE,USER_DETAILS_GRAHAKID,USER_DETAILS_FULLNAME,USER_DETAILS_EARNED_POINTS FROM USER_DETAILS";
	public static final String USER_TRANSACTON_INSERT ="INSERT INTO USER_TRANSACTIONS (USER_TRANSACTIONS_GRAHAKID,USER_TRANSACTIONS_USER_NUMBER,USER_TRANSACTIONS_FOOD_PURCHASED,USER_TRANSACTIONS_NONFOOD_PURCHASED,USER_TRANSACTIONS_TOTAL_AMOUNT_PURCHASED,USER_TRANSACTIONS_EARNED_POINTS,USER_TRANSACTIONS_CREATED_BY,USER_TRANSACTIONS_CREATED_ON,USER_TRANSACTIONS_CREATED_TIME) VALUES ";
	public static final String USER_SELECT_POINTS = "SELECT USER_POINTS_GRAHAKID,USER_POINTS_USER_POINTS FROM USER_POINTS_DETAILS WHERE";
	public static final String USER_INSERT_POINTS = "INSERT INTO USER_POINTS_DETAILS (USER_POINTS_GRAHAKID,USER_POINTS_USER_POINTS,USER_POINTS_CREATED_BY,USER_POINTS_CREATED_ON,USER_POINTS_CREATED_TIME) VALUES ";
	public static final String USER_UPDATE_POINTS = "UPDATE USER_POINTS_DETAILS SET ";
	
	/**
	 * Product Queries
	 */
	public static final String PRODUCTS_INSERT = "INSERT INTO PRODUCTS(PRODUCTS_NAME,PRODUCTS_MRP,PRODUCTS_GPPRICE,PRODUCTS_POINTS) VALUES";
	public static final String PRODUCTS_SELECT = "SELECT * FROM PRODUCTS";
	public static final String PRODUCTS_UPDATION = "UPDATE PRODUCTS SET ";
	public static final String CUST_PRODUCTS_UPDATION = "UPDATE CUSTPRODUCTS SET ";
	
	/**
	 * ITEMS_master Queries
	 */
	public static final String SELECT_ITEMS_MASTER = "SELECT ITEMS_MASTER_ID, ITEMS_MASTER_NAME,ITEMS_MASTER_RETAILMRP,ITEMS_MASTER_WAREHOUSEMRP,ITEMS_MASTER_STA,ITEMS_MASTER_CREATED_BY,ITEMS_MASTER_CREATED_ON,ITEMS_MASTER_CREATED_TIME,ITEMS_MASTER_UPDATED_BY,ITEMS_MASTER_UPDATED_ON,ITEMS_MASTER_UPDATED_TIME FROM ITEMS_MASTER ";
	public static final String ITEMS_CREATION = "INSERT INTO ITEMS_MASTER( ITEMS_MASTER_NAME,ITEMS_MASTER_RETAILMRP,ITEMS_MASTER_WAREHOUSEMRP,ITEMS_MASTER_STA,ITEMS_MASTER_CREATED_BY,ITEMS_MASTER_CREATED_ON,ITEMS_MASTER_CREATED_TIME) VALUES ";
	public static final String ITEMS_UPDATION = "UPDATE ITEMS_MASTER SET ";
	/**
	 * RETAIL QUERIES
	 */
	public static final String SELECT_RETAILERS_DETAILS = "SELECT RETAILERS_MASTER_ID, RETAILERS_MASTER_NAME,RETAILERS_MASTER_PASSWORD,RETAILERS_MASTER_DESCRIPTION,RETAILERS_MASTER_STA,RETAILERS_MASTER_CREATED_BY,RETAILERS_MASTER_CREATED_ON,RETAILERS_MASTER_CREATED_TIME,RETAILERS_MASTER_UPDATED_BY,RETAILERS_MASTER_UPDATED_ON,RETAILERS_MASTER_UPDATED_TIME FROM RETAILERS_MASTER";
	public static final String RETAILERS_CREATION = "INSERT INTO RETAILERS_MASTER(RETAILERS_MASTER_NAME,RETAILERS_MASTER_PASSWORD,RETAILERS_MASTER_DESCRIPTION,RETAILERS_MASTER_CREATED_BY,RETAILERS_MASTER_CREATED_ON,RETAILERS_MASTER_CREATED_TIME) VALUES ";
	public static final String RETAILERS_UPDATION = "UPDATE RETAILERS_MASTER SET ";
	
	/**
	 * shop order
	 */
	public static final String SELECT_SHOP_ORDERS = "SELECT SHOP_ORDERS_ID,SHOP_ORDERS_DATE_OF_PURCHASE,SHOP_ORDERS_QUANTITY,SHOP_ORDERS_PRICE,SHOP_ORDERS_REMARKS,SHOP_ORDERS_RETAILER_ID,SHOP_ORDERS_STATUS,SHOP_ORDERS_TOTAL_VALUE,SHOP_ORDERS_SHOPPY_ID";
	public static final String SHOP_ORDERS_INSERT = "INSERT INTO SHOP_ORDERS(SHOP_ORDERS_ID,SHOP_ORDERS_DATE_OF_PURCHASE,SHOP_ORDERS_QUANTITY,SHOP_ORDERS_PRICE,SHOP_ORDERS_REMARKS,SHOP_ORDERS_RETAILER_ID,SHOP_ORDERS_STATUS,SHOP_ORDERS_TOTAL_VALUE,SHOP_ORDERS_SHOPPY_ID) VALUES ";
}
